/**
 * Autogenerated by Postman CLI (postman mock generate)
 */
const http = require('http');
const PORT = process.env.PORT || 4010;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint GET /api/patients/:id
  if (req.method === 'GET' && /^\/api\/patients\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "No such patient" — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"text/plain"});
      return res.end("");
    }

    // "The patient" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":1001,"mrn":"MRN-001","status":"inactive","created_at":"2021-01-14T02:50:38.069Z","updated_at":"1989-07-17T04:58:29.320Z","first_name":"Ava","last_name":"Reyes","dob":"1988-03-14","identity_sub":"string","email":"ava.reyes@example.com","phone":"+1-555-0110","blood_type":"O+"}));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
